### ISSUE TITLE
4.3 Grader Report last row is not sticky

### ISSUE THREAD

**Issue by noisyjerm** [moodle-an-hochschulen/moodle-theme_boost_union#426] opened 2023-10-17 03:31 UTC
**Steps**
Visit a course with activities, students and grades
Open the grader report /grade/report/grader/index.php?id=123

**Expected**
The last row of the table labelled "Overall Average" is positioned at the end of the table and remains visible / sticks to the new footer when scrolling down the page.

**Actual**
The last row of the table labelled "Overall Average" overlaps the last user row. It scrolls with the page and does not stick to the top of the filter disappearing when you scroll down.

**Comment by abias** [comment] 2023-11-01 07:01
Hi @noisyjerm ,

thank you for reporting this issue. 
I think I understand the issue which you describe, but I was not able to reproduce it on Moodle 4.3 myself. 

May I ask you to re-test it with the Boost Union release v4.3-r1 which was just tagged and the latest Moodle core 4.3 version? May I ask you as well to do a countercheck with Boost core to verify that this glitch really just happens with Boost Union for you?

If you still encounter this issue, please submit a short screenrecording which visualizes this glitch.

Cheers,
Alex

**Comment by noisyjerm** [comment] 2023-11-05 22:24
I have tested with v4.3-r1 and it all works as expected. I believe the issue lies within my own additional SCSS.

Thanks
Jeremy

**Comment by abias** [comment] 2023-11-06 06:40
Allright, thank you for your confirmation!
Then we can close this issue.

**Closed by abias** 2023-11-06 06:40 UTC
Labels: discussion needed, upgrade, affecting 4.3 only
