### ISSUE TITLE
Close option on one info banner

### ISSUE THREAD

**Issue by cdipe** [moodle-an-hochschulen/moodle-theme_boost_union#744] opened 2024-10-24 12:55 UTC
**Describe the bug**
The close option is only on one info banner

**To Reproduce**
1. Go to https://moodlesite/admin/settings.php?section=theme_boost_union_content#theme_boost_union_infobanners_infobanner
2. Create one time controlled info banner
3. Create another time controlled info banner (use same settings as the first banner)
4. Only the first created info banner will have the close option

**Expected behavior**
All info banners should have the close option

**Screenshots**
![image](https://github.com/user-attachments/assets/d8f0f131-e91e-40e0-9441-b3778d2ab2e1)

**Additional context**
Moodle version: 4.1.13
Boost Union version: v4.1-r29

**Comment by HsH-Wolf** [comment] 2024-10-28 10:23
Hello @cdipe, 

I tried to reproduce this behaviour, but everything works fine, if I set dismissible to "yes" for both banners:

![grafik](https://github.com/user-attachments/assets/61890ac8-4c7c-4bf9-b136-fc3f50e681c2)

Best regards
Yvonne

**Comment by cdipe** [comment] 2024-11-04 10:05
Hi @HsH-Wolf, did you create a time controlled banner? In the version we use the admin option to make the banner dismissable disappears when selecting "Time controlled". The option is still visible to the user though, as shown in my image, so I thought it should be there... I guess I'll change the time setting to "Perpetual" and put reminders in the calendar instead.
Do you know how v4.5 works? I'll make an improvement suggestion to have an option to make also the time controlled banner "permanently dissmissable", if it's not already so in that version.

**Comment by wiebkemueller-hsh** [comment] 2024-11-06 12:31
Hi @cdipe 

the banner is either permanently shown (and then permanently dismissable by users) or time controlled. The close option "x" in the banners (when configured as time bHi @cdipe 

the banner is either permanently shown (and then permanently dismissable by users) or time controlled. The close option "x" in the banners (when configured as time controlled) are always shown but misleading since the banner always reappears after page reload. It is what I would call a discussable but sometimes desirable behaviour b/c you might want to force users to see the banner, but then why show the close option?

**I agree with you that there are reasons to just not show the x if the x isn't removing the thing for good. So feel free to work out a logic for an improvement of the not yet existant "time controlled + permanently dismissable" - option, we can use this issue to be marked as an improvement.**

This feature hasn't been touched in the 4.5 release. So for now - in your case I would stick to the already considered option to individually set a private calendar reminder to remove the banner if you want your users to be able to permamently remove the banner. In our case we use the timebased option only for noticing about e.g. an approaching maintenance time slot etc.  - this never shows longer than one afternoon and we simply never cared about the being dismissable or not options in that case.

Regards on behalf of the team!
Wiebke

**Comment by wiebkemueller-hsh** [comment] 2024-11-06 12:39
Hello again @cdipe, 

I have to correct myself in one point: In the current release 4.5-r2 (and problably also other versions between 4.1 and 4.5) the time controlled banner has no more closing option x shown! So nothing more misleading here, there are 2 options: permanently shown (and then permanently dismissable by users) or time controlled. 
You can still think about to propose a logic for a combination of both.

Regards
Wiebke

![grafik](https://github.com/user-attachments/assets/001c062f-8c7c-4328-86fa-ff08bd0a677c)

**Comment by cdipe** [comment] 2024-11-06 12:41
@wiebkemueller-hsh Thank you, I'll make a proposal :)

**Comment by HsH-Wolf** [comment] 2024-11-07 09:50
See proposal:
[[ Option to dismiss time controlled info banners #748 ]( Option to dismiss time controlled info banners #748 )](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/748)

**Closed by HsH-Wolf** 2024-11-07 09:50 UTC
