### ISSUE TITLE
Bug: Images uploaded to the Atto editor for content pages save with draftfile in the url and are not accessible for all users

### ISSUE THREAD

**Issue by james-pearce-bath-ac** [moodle-an-hochschulen/moodle-theme_boost_union#197] opened 2023-01-17 16:11 UTC
We have noticed that when adding content to the content pages in the theme via the Atto editor the images are uploaded and saved to the server. The file path is not generated fully and the path has draftfile in it. This means only the user that has uploaded the file can see the images. 

We have worked around the issue by referencing the files uploaded to the additional resources section.

Having worked on a similar issue with a plugin we were developing I found this guidance helpful https://moodledev.io/docs/apis/subsystems/form/usage/files

**Comment by abias** [comment] 2023-01-20 06:41
Thank you for reporting this issue, @james-pearce-bath-ac .

I have to admit that, when the static pages were implemented, adding images and other files to them within the Atto editor was not within the scope.

We will have a look at the bug soon.

**Comment by abias** [comment] 2023-01-29 15:40
Hi @james-pearce-bath-ac ,

thanks again for reporting this issue.

I just had a closer look and tried to reproduce this issue, but I didn't manage to reproduce it. In my tests, the Atto editors on the "static pages" settings tab do not have the possibility to upload images at all - you can just link to existing images:

<img width="1431" alt="grafik" src="https://user-images.githubusercontent.com/1092118/215337287-10c9c1eb-9bbe-4a37-bd92-8ec1ab10233d.png">

I basically know how the issue with the draftfile URL which you described feels like. And I also know that you can instantiate Atto editors with or without the possibility to upload images within the editor. However, as far as I see, this upload possibility is always off for Atto editors which are instantiated within a `admin_setting_confightmleditor` admin settings.

But I may be wrong or I may be missing something. That's why I would like to ask you to provider clear [steps to reproduce](https://docs.moodle.org/401/en/How_to_add_steps_to_reproduce_to_a_bug_report) and ideally screenshots so that I can understand what's happening on your side.

Thanks,
Alex

**Comment by james-pearce-bath-ac** [comment] 2023-01-31 17:01
hi @abias, thanks for looking into this. The issue was originally raised by a colleague of mine and I've gone back to them today to get some more clarification. I misunderstood their request they wanted to kknow if the suggested flow of adding the link to the additional resourses uploads was the expected process. I'm happy for this ticket to be closed.

**Comment by lucaboesch** [comment] 2023-02-01 07:17
Thanks, @james-pearce-bath-ac .
Closing

**Closed by lucaboesch** 2023-02-01 07:17 UTC
Labels: bug

**Comment by abias** [comment] 2023-02-01 07:24
Thanks @james-pearce-bath-ac ,

> I misunderstood their request they wanted to kknow if the suggested flow of adding the link to the additional resourses uploads was the expected process. 

Thank you for your clarification. Now your explanation makes sense. And yes, the workaround with the additional resources uploads seems to be the only feasible way at the moment.

I do not see a possibility to add an image upload to a admin_setting_confightmleditor element in the admin settings. If we would want to add that, we would have to extend that class in the theme which is out of scope at the moment.

However, if you really want to see that, don't hesitate to create a fresh issue as feature request (independently from this misleaded bug report here).

Cheers,
Alex
