### ISSUE TITLE
 When viewing a single section, the pull-down menu for sections shows only one section.

### ISSUE THREAD

**Issue by monnardj** [moodle-an-hochschulen/moodle-theme_boost_union#639] opened 2024-04-25 07:28 UTC
In Moodle 4.4, clicking on a section title displays only the corresponding section (this is a standard feature which cannot be disabled). 

When the "Activity and section navigation" is enabled, the pull-down menu at the bottom doesn't work correctly :

1. When any section except the last one is displayed individually, the menu shows only the last section :

<img width="862" alt="image" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/5880250/705b50f9-1f9b-4408-9346-23998c9bbe42">

2. When the last section is displayed, the menu shows only the previous section. Clicking on this section sends the user back to the course home page with all sections.

<img width="918" alt="image" src="https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/5880250/a49bf5a9-ccff-43f2-834c-637f4e7c4d26">

Normally, this menu should display all sections except the current one, with a first link "Main course page", just like in previous versions, when "Show one section per page" was selected under the course format options.

**Comment by HsH-Wolf** [comment] 2024-05-23 07:41
Dear @monnardj 

There might appear some unexpected behaviour, since there is no Boost Union Version for moodle 4.4, yet. We are working on it and hope to release it, soon.

Best regards on behalf of the boost union team.

**Comment by abias** [comment] 2024-07-04 19:40
Hi @monnardj ,

thank you for highlighting this issue.
I can reproduce this issue on Moodle 4.4 with Boost Union. However, I have state that this is a Moodle core bug and not a Boost Union issue.

The `activitynavigation` setting in Boost Union just does one thing: It sets the `$PAGE->theme->usescourseindex` property to `false`. This way, the theme can indicate to Moodle core that it does not have a course index and that Moodle core should show the activity navigation like it has done in former times.

Please switch your active theme to Classic which sets the same property to false - as it does not have any course index obviously. And you will see this bug in Classic as well.

I have reported this core bug on https://tracker.moodle.org/browse/MDL-82391 now and will leave this issue here open for others who might encounter it until it is fixed in Moodle core.

**Comment by abias** [comment] 2024-07-10 18:28
If you watch https://tracker.moodle.org/browse/MDL-82391, you will see that this issue has already a patch and will be fixed in Moodle core soon.

**Comment by abias** [comment] 2024-07-12 06:24
This issue was solved in Moodle core now and will be part of next week's weekly release of Moodle core. Nothing to do for us here anymore.

**Closed by abias** 2024-07-12 06:24 UTC
Labels: waiting for fix in core, affecting 4.4 only
