### ISSUE TITLE
I can't delete pictures in the Login page background section

### ISSUE THREAD

**Issue by ipaneman006** [moodle-an-hochschulen/moodle-theme_boost_union#746] opened 2024-11-02 19:19 UTC
Hello, I have the moodle-theme_boost_union working on a Moodle 4.5. 

I put some background pictures for the login page in Appearance, then click on Look, click on login page. The issue is that I want to delete some of them. For this, I select the images that I want to delete and click the dustbin button, but nothing happens. In normal conditions, a pop up window should appear with a message more or less like this: "Are you sure you want to delete this file?". But as I said, this won't show up and nothing happens. 

I've already checked to see if it was the browser that was blocking the pop-ups, but it was fine and I've even tried with different browsers and the result is the same.

Any idea of what could be wrong?

Thanks in advance!

**Comment by wiebkemueller-hsh** [comment] 2024-11-06 13:23
Hi @ipaneman006 

I will close this as we were not able to reproduce this, tested with a Moodle 4.5 (Build: 20241007) and Boost Union version: TAG:v4.5-r2 in Firefox and Chrome on Windows 10 Enterprise. 

Any idea on any other alterations you may have in place in your installation? Please note for support there is also the forum thread with many users watching, in case anybody else encountered that behaviour.

Regards on behalf of the team
Wiebke

**Closed by wiebkemueller-hsh** 2024-11-06 13:23 UTC
Labels: new
