### ISSUE TITLE
Maintenance Schedule Count Down not shown on any page

### ISSUE THREAD

**Issue by toyinal1200** [moodle-an-hochschulen/moodle-theme_boost_union#725] opened 2024-10-07 11:42 UTC
Hi,

How to reproduce
On the command line type php /var/www/moodle/admin/cli/maintenance.php --enablelater=10
to schedule maintenance mode in 10 minutes.
A Maintenance Schedule Counter, should show on the bottom right of any page, However it is not showing.
Im currently on Boost Union version v4.3-r14
Server: Moodle 4.3.7, PHP 8.0, NGINX, DEBIAN 12 (bookworm)
 User System: HP Elitebook 720, Windows 11, Chrome, Firefox, MS Edge  Web Browser

Thanks

**Comment by abias** [comment] 2024-10-25 05:58
Hi @toyinal1200 ,

thanks you very much for reporting this issue.
I am struggling to reproduce your issue as the maintenance schedule countdown works for me quite well.

May I ask you these questions:
1. Do you encounter the same problems with theme Boost (from Moodle Core) as well or only with Boost Union?
2. Do you expect the maintenance schedule countdown to show directly after you activated it with the CLI command, i.e. without a page reload in the browser? If yes, then I have to tell you that this is not supported in Moodle, but you can give another plugin of ours (https://moodle.org/plugins/local_maintenance_livecheck) a try to fix this gap.
3. Do you miss the maintenance schedule countdown on _all_ Moodle pages or just on some of them? If you miss it on just some pages, please give us a list.

Cheers,
Alex

**Comment by toyinal1200** [comment] 2024-10-27 05:33
Thanks for your response, I was actually testing the Maintanenace_mode LiveCheck plugin set to the default interval of 60 secs with 0 backoff time. After enabling delayed Maintenance Mode for 10 mins lwith the command line type php /var/www/moodle/admin/cli/maintenance.php --enablelater=10 .
No Countdown was displayed on ANY Page.
- Same problem with Boost Union, Boost core theme and Classic core theme.

I will be grateful if you can point me in right direction to debug this.

Thanks

**Comment by abias** [comment] 2024-11-04 19:45
Hi @toyinal1200 ,

thanks for your clarification.
As you confirmed that this is not a Boost Union problem and as you have raised a similar issue on https://github.com/moodle-an-hochschulen/moodle-local_maintenance_livecheck/issues/4, I will close this issue here.

Cheers,
Alex

**Closed by abias** 2024-11-04 19:45 UTC
Labels: discussion needed
