### ISSUE TITLE
Improvement - gradebook spacing

### ISSUE THREAD

**Issue by buddy1234567** [moodle-an-hochschulen/moodle-theme_boost_union#382] opened 2023-09-01 16:55 UTC
At the moment, gradebook vertical spacing is, in my view, highly excessive and prohibits a teacher from seeing much of their student roster.  Attached are two screenshots:  the current gradebook and a suggested revised model.  Granted the current gradebook is more visually appealing due to its sparceness, but the suggested model is far more functional.  After all, do teachers want to see 4 students at once, or 12, or more...?

![gradebook-og](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/34031812/ddf92d2d-3b9d-4e01-9ec5-633f9c6fbd03)
![gradebook-revised](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/34031812/e0536a36-888c-4895-b9e8-17152e668801)

**Comment by lucaboesch** [comment] 2023-09-02 14:55
I don't think that should be theme specific, @buddy1234567 and I would encourage you to open an issue on https://tracker.moodle.org

**Comment by buddy1234567** [comment] 2023-09-03 01:46
Hmmm.  I thought everything that isn't functional is UI.  This seems very much related to theme to me.

**Comment by pkgh** [comment] 2023-09-03 10:02
I think a good (maybe the best) place for discussing the issue is the UX forum : https://moodle.org/mod/forum/view.php?id=8698 .

**Comment by wiebkemueller-hsh** [comment] 2023-10-05 09:38
Hello @buddy1234567 

we are currently in the situation of having to prioritise issues. this got a won't fix, out of the reasons stated above. feel free to edit a moodle tracker, the problem as such is absolutely justified.

Regards
Wiebke

**Comment by wiebkemueller-hsh** [comment] 2023-10-05 09:39
.

**Closed by wiebkemueller-hsh** 2023-10-05 09:39 UTC
Labels: wontfix
