### ISSUE TITLE
Items display in Recently accessed items block for Moodle 4.4 (enhancement)

### ISSUE THREAD

**Issue by luiggisanso** [moodle-an-hochschulen/moodle-theme_boost_union#663] opened 2024-05-30 11:57 UTC
**Describe the bug**
The items are not clearly displayed

In order to prepare the new 4.4 Boost_Union version, I have tested the last 4.3 version on a personnal 4.4 Moodle.
And the Reclently accessed items block can be better with other CSS rules.

**Expected behavior**
View with Boost theme
![image](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/1565841/9ed35310-8541-428a-b923-5549c3fc6619)

View with Boost_Union theme
![image](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/assets/1565841/0fbfaa6a-120d-4e5a-9289-a0b8bc70cde0)

**Comment by lucaboesch** [comment] 2024-05-30 12:56
This is related to MDL-80397 and the changes in the upstream template therein.
I reckon the adopted boost_union template has to be adopted and the issue is gone.

**Comment by lucaboesch** [comment] 2024-05-30 13:10
As soon as Boost Union development for Moodle 4.4 really starts, in https://github.com/lucaboesch/moodle-theme_boost_union/tree/blockrecentlyaccesseditems there is a solution for this.
I will finish that patch accordingly at that point in time.

Best,
Luca

**Comment by luiggisanso** [comment] 2024-05-30 13:41
Perfect @lucaboesch 

If you want/need some tests, don't hesitate too :-D

**Comment by abias** [comment] 2024-07-04 16:18
Hi all,

this issue has now been fixed for Moodl 4.4 in 7169228c5dcea61b1646272998f7ebe5ff245bce.
This commit is located in the [upgrade-404](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/commits/upgrade-404/) branch which will be merged in the main branch as soon as the whole Moodle 4.4 upgrade work is done.

Cheers
Alex

**Closed by abias** 2024-07-04 16:18 UTC
Labels: affecting 4.4 only
