### ISSUE TITLE
Bug: error message in content tab

### ISSUE THREAD

**Issue by ralf-krause** [moodle-an-hochschulen/moodle-theme_boost_union#198] opened 2023-01-20 06:46 UTC
I get an error message in debug mode at the bottom of the content tab.

```
Too much data passed as arguments to js_call_amd("core/showhidesettings", "init"). Generally there are better ways to pass lots of data from PHP to JavaScript, for example via Ajax, data attributes, ... . This warning is triggered if the argument string becomes longer than 1024 characters.

    line 1066 of /lib/outputrequirementslib.php: call to debugging()
    line 173 of /admin/settings.php: call to page_requirements_manager->js_call_amd()
```

**Comment by abias** [comment] 2023-01-20 07:18
Hi Ralf,

thank you for reporting this issue.

The short answer:
This is a debug message and not a bug. Everything is working fine.

The longer answer:
Boost Union has many settings and we are expecially using the hide_if feature of the admin settings framework heavily to hide and show settings depending on other settings.
Unfortunately, under the hood, the hide_if feature is using an rather outdated Moodle core method to pass arguments to the JavaScript code in the HTML page which can trigger issues with large amounts of data to be passed. Moodle core has a built-in warning to inform the developer as soon as you are passing too much data with this Moodle core method and asks you to refactor your code to avoid problems in the future.
However, this is a problem of Moodle core. It is not a problem of Boost Union. We are just seeing the symptoms in Boost Union. And I can say that I have never experiences any issues with this feature up to now in any browser.
We can't solve this issue in Boost Union, it would have to be solved in Moodle core and it would be quite a bit of effort. I am not aware that there is even a Moodle tracker issue for this need.

Against this background, I can tell you:
Just ignore the debug message which you are only seeing on certain Boost Union settings pages if you are turning debug mode on. In Boost Union's Behat tests, we are doing the same (for example on https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/blob/ad26c85b08e1369c026b942966fbc69e114f66db/tests/behat/theme_boost_union_contentsettings_infobanners.feature#L196) as otherwise, the debug message would let our tests fails for no reason.

So I will close this as "Won't fix".

Cheers,
Alex

**Closed by abias** 2023-01-20 07:18 UTC
Labels: bug, wontfix

**Comment by ralf-krause** [comment] 2023-01-20 14:12
I created a tracker issue https://tracker.moodle.org/browse/MDL-76975
Could you please tell me which modul team should be addressed to fix the error? I thing that the Themes modul is wrong.
